### ISSUE TITLE
gradle plugin should be published to https://plugins.gradle.org/

### ISSUE THREAD

**Issue by johnscancella** [junit-team/junit5-samples#24] opened 2017-05-02 17:26 UTC
instead of forcing gradle users to use the old notation for plugins i.e.
```
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M4'
	}
}

apply plugin: 'org.junit.platform.gradle.plugin'
```
you should instead publish to https://plugins.gradle.org/ so that gradle users can use the much preferred syntax of 
```
plugins {
  id 'org.junit.platform.gradle.plugin' version '1.0.0-M4'
}
```

**Comment by marcphilipp** [comment] 2017-05-03 04:44
Duplicate of junit-team/junit5#768.

**Closed by marcphilipp** 2017-05-03 04:44 UTC
